### ISSUE TITLE
Xcode debugging

### ISSUE THREAD

**Issue by kpgalligan** [SimonSchubert/NewsOut#1]
I didn't want to submit a PR as I have no idea if you want this, but I wanted to test setting up Xcode debugging on another project.

If you want to see Xcode debugging on your project, I have a fork branch with everything set up. More info about Kotlin Xcode debugger: https://hackernoon.com/kotlin-xcode-plugin-64f52ff8dc2a

https://github.com/kpgalligan/Newsout/tree/kpg/add_xcode_debugging

**Comment by SimonSchubert** [comment]
What a pleasure to meet you, President of Touchlab.

PR's are very welcome, I will make that clear in the readme.

I briefly heard about the plugin but had no time to test it out, yet. In your commit (https://github.com/kpgalligan/Newsout/commit/710c16833f0a7e2c161be342cfb080398cdf4a25) in the build.gradle.kts file you are pointing to an absolute path for the plugin. Would it make sense to add the plugin to the project itself and have a relative path instead? Or even better a public repository?

**Comment by kpgalligan** [comment]
Sorry! That was a mistake. I'm testing that gradle plugin locally, so I was pointing at a local repo. They're definitely published to a public repo (mavenCentral): https://search.maven.org/artifact/co.touchlab/kotlinxcodesync/0.1.4/jar.

I'll clean this up and update a little later. I'm adding dependency support now, so you should be able to also add dependency source files.

**Comment by SimonSchubert** [comment]
That's great news. I'm looking forward to the PR.

**Comment by SimonSchubert** [comment]
I just added the plugin manually, it's super handy and easy to set up. Absolute great work 👍 👍 👍
