### ISSUE TITLE
The newsout app provided nextcloud sever is unreachable 10/15

### ISSUE THREAD

**Issue by Locash** [SimonSchubert/NewsOut#3]
Newsout provided Nextcloud [server](https://nx3217.your-next.cloud/) is currently unreachable. Is this a temporary problem, or has the provided server been retired/discontinued?

**Comment by SimonSchubert** [comment]
The provider permanently changed the url. I will fix and reupload a version to the stores asap. Thanks

**Comment by SimonSchubert** [comment]
I just released an update (v.1.2.2) to the Play Store and F-Droid store. It might take a few hours until it's available to download.
